all: first second

first:
	javac -d ./web -cp /home/cooper/school/networks/prog3/bin ./src/WebServer.java

second:

a:
	vim /home/cooper/school/networks/prog3/src/WebServer.java

run:
	make -C ./web run
